name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Build project
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

  pr-size-check:
    name: PR Size Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Check PR size
      run: |
        # Check the number of lines changed
        LINES_CHANGED=$(git diff --stat ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tail -1 | awk '{print $4+$6}')
        if [ "$LINES_CHANGED" -gt 1000 ]; then
          echo "PR is too large ($LINES_CHANGED lines changed). Consider splitting into smaller PRs."
          exit 1
        fi

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v4

  pr-lint:
    name: PR Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Check for TODO comments
      run: |
        # Count TODO comments (excluding tests and generated files)
        TODO_COUNT=$(find src -name "*.rs" -not -path "*/tests/*" -not -name "*generated*" -exec grep -l "TODO\|FIXME\|XXX" {} \; | wc -l)
        if [ "$TODO_COUNT" -gt 0 ]; then
          echo "Found TODO/FIXME comments in source code. Please address them or move to issue tracker."
          find src -name "*.rs" -not -path "*/tests/*" -not -name "*generated*" -exec grep -n "TODO\|FIXME\|XXX" {} \;
        fi
